import React from 'react';
import { PlayerOptions } from 'boclips-player';
import { Video } from 'boclips-api-client/dist/sub-clients/videos/model/Video';
import { Player } from 'boclips-player-react';
import BoclipsSecurity from 'boclips-js-security';

const getPlayerOptions = (): Partial<PlayerOptions> => {
  const security = BoclipsSecurity.getInstance();
  const tokenFactory = security.getTokenFactory(5);
  return {
    interface: {
      controls: [
        'play-large',
        'play',
        'progress',
        'current-time',
        'mute',
        'volume',
        'captions',
        'fullscreen',
        'settings',
      ],
      ratio: '16:9',
    },
    displayAutogeneratedCaptions: false,
    api: {
      tokenFactory: async () => {
        try {
          return await tokenFactory();
        } catch (error) {
          throw error('Please log in to view this video');
        }
      },
    },
  };
};

interface Props {
  video: Video;
}

export const VideoPlayer = ({ video }: Props) => (
  <Player
    videoUri={video.links.self.getOriginalLink()}
    borderRadius="4px"
    options={getPlayerOptions()}
  />
);
