import React from 'react';
import { PlayerOptions } from 'boclips-player';
import { Video } from 'boclips-api-client/dist/sub-clients/videos/model/Video';
import { Player } from 'boclips-player-react';
import BoclipsSecurity from 'boclips-js-security';
import s from './VideoPlayer.module.less';

const getPlayerOptions = (
  playerControls?: string,
  showDurationBadge?: boolean,
): Partial<PlayerOptions> => {
  const security = BoclipsSecurity.getInstance();
  const tokenFactory = security.getTokenFactory(5);

  const defaultControls: any[] = [
    'play-large',
    'play',
    'progress',
    'current-time',
    'mute',
    'volume',
    'captions',
    'fullscreen',
    'settings',
  ];

  const cartControls: any[] = [
    'play-large',
    'play',
    'progress',
    'current-time',
    'mute',
    'volume',
    'fullscreen',
  ];

  const controls = playerControls === 'cart' ? cartControls : defaultControls;

  return {
    interface: {
      controls,
      ratio: '16:9',
      addons: {
        videoLengthPreview: showDurationBadge,
      },
    },
    displayAutogeneratedCaptions: false,
    api: {
      tokenFactory: async () => {
        try {
          return await tokenFactory();
        } catch (error) {
          throw error('Please log in to view this video');
        }
      },
    },
  };
};

interface Props {
  video: Video;
  controls?: 'cart';
  showDurationBadge?: boolean;
}

export const VideoPlayer = ({
  video,
  controls,
  showDurationBadge = false,
}: Props) => {
  const options = getPlayerOptions(controls, showDurationBadge);

  return (
    <div className={s.playerWrapper}>
      <Player
        videoUri={video.links.self.getOriginalLink()}
        borderRadius="4px"
        options={options}
      />
    </div>
  );
};
