import React from 'react';
import { Video } from 'boclips-api-client/dist/sub-clients/videos/model/Video';
import { VideoCard } from '@boclips-ui/video-card';
import { convertVideoFromApi } from 'src/services/convertVideoFromApi';
import { PlayerOptions } from 'boclips-player';
import { Player } from 'boclips-player-react';
import AddToCartButton from 'src/components/addToCartButton/AddToCartButton';

interface Props {
  video: Video;
}

export const playerOptions: Partial<PlayerOptions> = {
  interface: {
    controls: [
      'play-large',
      'play',
      'progress',
      'current-time',
      'mute',
      'volume',
      'captions',
      'fullscreen',
      'settings',
    ],
    ratio: '16:9',
  },
  displayAutogeneratedCaptions: false,
};

export const VideoCardWrapper = ({ video }: Props) => {
  return (
    <VideoCard
      key={video.id}
      price={video.price?.displayValue}
      videoPlayer={
        <Player
          videoUri={video.links.self.getOriginalLink()}
          borderRadius="4px"
          options={playerOptions}
        />
      }
      border="bottom"
      video={convertVideoFromApi(video)}
      authenticated
      hideAttachments
      hideBestFor
      theme="publishers"
      videoActionButtons={[
        <AddToCartButton videoId={video.id} key="cart-button" />,
      ]}
      videoRoundedCorners
    />
  );
};
