import React from 'react';
import { Video } from 'boclips-api-client/dist/sub-clients/videos/model/Video';
import { convertVideoFromApi } from 'src/services/convertVideoFromApi';
import { PlayerOptions } from 'boclips-player';
import { Player } from 'boclips-player-react';
import AddToCartButton from 'src/components/addToCartButton/AddToCartButton';
import { VideoCardV2 } from '@boclips-ui/video-card-v2';
import { PriceBadge } from 'src/components/videoCard/PriceBadge';

interface Props {
  video: Video;
}

export const playerOptions: Partial<PlayerOptions> = {
  interface: {
    controls: [
      'play-large',
      'play',
      'progress',
      'current-time',
      'mute',
      'volume',
      'captions',
      'fullscreen',
      'settings',
    ],
    ratio: '16:9',
  },
  displayAutogeneratedCaptions: false,
};

export const VideoCardWrapper = ({ video }: Props) => {
  return (
    <VideoCardV2
      key={video.id}
      video={convertVideoFromApi(video)}
      videoPlayer={
        <Player
          videoUri={video.links.self.getOriginalLink()}
          borderRadius="4px"
          options={playerOptions}
        />
      }
      border="bottom"
      theme="publishers"
      topBadge={<PriceBadge price={video.price?.displayValue} />}
      actions={[<AddToCartButton videoId={video.id} key="cart-button" />]}
    />
  );
};
