export const enum AppcuesEvent {
  HOMEPAGE_SEARCH = 'HOMEPAGE_SEARCH',
  FILTERS_APPLIED = 'FILTERS_APPLIED',
  COPY_LINK_FROM_SEARCH_RESULTS = 'COPY_LINK_FROM_SEARCH_RESULTS',
  COPY_LINK_FROM_VIDEO_PAGE = 'COPY_LINK_FROM_VIDEO_PAGE',
  ADD_TO_CART_FROM_SEARCH_RESULTS = 'ADD_TO_CART_FROM_SEARCH_RESULTS',
  ADD_TO_CART_FROM_VIDEO_PAGE = 'ADD_TO_CART_FROM_VIDEO_PAGE',
  VIDEO_PAGE_OPENED = 'VIDEO_PAGE_OPENED',
  YOUR_ORDERS_OPENED = 'YOUR_ORDERS_OPENED',
  CART_OPENED = 'CART_OPENED',
  ORDER_CONFIRMED = 'ORDER_CONFIRMED',
}
